### ISSUE TITLE
Footnote topSkip abused if footnote comes too late to make space

### ISSUE THREAD

**Issue by alerque** [sile-typesetter/sile#214]
In the worst case scenario where a footnote marker is on the last line of a page, the footnote is added even though there isn't room for the frame, much less with the added value of `topSkip`. I'm not sure what the logic _should_ be in this scenario, but probably forcing the page to break a line earlier so the insertion happens on the next page would be in order.

![selection_108](https://cloud.githubusercontent.com/assets/173595/11265665/d2be61b4-8ea6-11e5-827e-9b519032ca43.png)

In that example `footnote.topSkip` is set to 3ex with no stretch values.

**Comment by alerque** [comment]
This is still not quite right. With the above fix in place it happens _much much_ less often, but it still happens. Case in point:

![selection_113](https://cloud.githubusercontent.com/assets/173595/11429739/137ebc6a-9485-11e5-8d77-d63d8f76f6f6.png)

Besides the case of outright overlaps, the case of the topSkip being disregarded and ending up much-compressed for no apparent reason is suddenly more common:

![selection_114](https://cloud.githubusercontent.com/assets/173595/11429770/8c0f370e-9485-11e5-894a-4674aad32218.png)

Above the and left page is close enough but the middle is compressed: not to 0 in this case but to less that 1ex where the document dictates it should be at least 2.5ex.

**Comment by simoncozens** [comment]
Looks like this is fixed now?

**Comment by alerque** [comment]
Sadly, I don't think so. I just ran on the latest build and still have a number of instances of the topSkip boing ignored. I'm not sure if this is the _same_ issue though. For example footnote 13 here got pushed over from the previous page, which is great, but it ignored topSkip when it came:

![selection_118](https://cloud.githubusercontent.com/assets/173595/11457293/a04f0c2e-96ad-11e5-91ef-401be2d06fc9.png)

Mostly it's just squishing the topSkip to zero, but occasionally it still overlaps. I think most of these are actually a different bug because they aren't in cases where the footnote marker came late on the page, as in this:

![selection_119](https://cloud.githubusercontent.com/assets/173595/11457265/e300338c-96ac-11e5-88a5-2b830cf95550.png)

But that being said, that same thing is happening when the footnote marker does come late, as in this:

![selection_120](https://cloud.githubusercontent.com/assets/173595/11457298/c06084ca-96ad-11e5-82bd-c31e6a08af8e.png)

In that case footnote 2 did get split like it needed to be given where the marker came, and it did use topSkip on the _next_ page, but it got abused on the page where the footnote started.

**Comment by alerque** [comment]
Here are two more cases where the footnote marker coming late in the page is causing the topSkip to be ignored rather than push the note to the next page.

![selection_121](https://cloud.githubusercontent.com/assets/173595/11457367/798e4b3e-96af-11e5-8beb-e1f03d996549.png)

**Comment by alerque** [comment]
Nevermind. Scratch the above, my testing routine was bad. A run with the actual right software looks good. I think. I'll re-open if I have something legit to report.

**Comment by alerque** [comment]
Nevermind the nevermind. My testing was fine, I just borked the leading method so everything moved around and the failure cases were all elsewhere. It really is still doing exactly as described above, just in different places because the leading is different.

**Comment by alerque** [comment]
Here is another interesting case where this is failing. In this example the footnote that was too big to fit (6) did get pushed to the next page, but it didn't seem to notice when typesetting the last line on the page that it wasn't just adding that last footnote that was too much, the previous footnote (5) also didn't fit. The last line of content should have been push to the next page, not just the footnote:

![selection_126](https://cloud.githubusercontent.com/assets/173595/11469038/6ce06004-975c-11e5-9abc-4fa73a513e0d.png)

**Comment by alerque** [comment]
I don't know if this is useful information or something you don't already know, but I was trying to figure out any way to set the skip distance from content to footnotes and started playing with frames. It turn out most of the egregious cases of not having any space, the content is actually overflowing the content frame. The footnotes frame is growing and the content is shrinking in such a way that they _should_ be clear of each-other, but the content isn't staying it it's box. Possibly related to #234.

![selection_129](https://cloud.githubusercontent.com/assets/173595/11475612/fad09602-9786-11e5-971a-c4fe5d9caf8c.png)

**Comment by simoncozens** [comment]
At this point I think I'm going to throw out the insertions code and try again. The current system of trying to join multiple insertion boxes together into a frame is clearly wrong; there should be one box, with the content in it. That will certainly fix up this but and #213 as well.

**Comment by alerque** [comment]
That would enable for footnote layouts such as having them all on the same line instead of in separate paragraphs ([example pdf](http://www.wtsbooks.com/common/pdf_links/9781433530302.pdf)).

**Comment by simoncozens** [comment]
Please try the new-insertions branch. It's experimental but it seems to do a lot better job on your document. Let me know if there are any bits that don't work as you expect.

**Comment by alerque** [comment]
Would you like separate issues posted against that branch or should I just mention them here? So far I have:

* topSkip is still abused. Sometimes some space is there, but nothing I set seems to keep it reliably offset from the main content, and sometimes it still runs in. Setting skips in \footnote:separator is ignored entirely, and manually stuffing topBox with even huge Vglue's doesn't keep the footers from sometimes overlapping the main content.
* muliti-line footnotes don't work. They start normally and do wrap, but the wrap isn't taken into account by subsequent footnotes which start where they would have if the previous one hadn't wrapped. If the last footnote on the page wraps it runs off the page instead of pushing the content frame up.
* something isn't getting cleared right. For some reason at most commonly at chapter breaks but also at other places, some subset of all the previous chapter's footnotes get dumped into the insertion space. Again.

**Comment by simoncozens** [comment]
Um. That's weird. I just committed some tests which exercise items 1 and 2 above, and they seem to work...

**Comment by simoncozens** [comment]
OK, I see it too. Grump.

**Comment by simoncozens** [comment]
It's a clash with the linespacing package. Don't know why, but I'll work on it.

**Comment by alerque** [comment]
Huh. Of the three items above, only number 3 is still happening if I drop the linespace package and use the default leading system. I'll play around with it in that mode and see if I can come up with typesetting that looks good, but there were some advantages to the fit-font algorithm. Let me know if I can do anything that will be useful to you on this issue.

**Comment by simoncozens** [comment]
See if d7d792d helps you with number 3.

**Comment by alerque** [comment]
No, I still see number 3. Here is [what it looks like](https://cloud.githubusercontent.com/assets/173595/11531053/8cc840c4-9902-11e5-8d5a-eb0fcc599f9c.png) in case my description wasn't clear. It seems to happen with or without the linespacing package.

**Comment by simoncozens** [comment]
OK. I think we are now a bit closer. Try again as of 2979c32! I haven't made it work with linespacing, (that's tomorrow's job) but the ordinary leading algorithm seems to work.

**Comment by simoncozens** [comment]
And now closer still. Inconsistent leading is separate, but I should have fixed both this and #229 as well.

**Comment by alerque** [comment]
I'm re-opening this because the bug has re-incarnated. The current test file does not trigger it, but tweaking the content a bit so the metrics pose a different scenario triggers the same behavior. I was trying to fix this is my measurements refactoring, but gave up when I realized it was actually broken in master too. I'll work on it after I finish cleaning up the things I actually broke. I'll update the test to illustrate the problem again and mark it as known-bad for now.
