### ISSUE TITLE
Page break resets rskip/lskip. Sometimes.

### ISSUE THREAD

**Issue by alerque** [sile-typesetter/sile#262]
Since the fix for #255 I have an elusive issue with my block quote environments that have lskip/rskip values applied. Sometimes when a page break happens inside the environment, the next page will not be properly typeset. What's funny is the font settings are coming across, but not the adjusted margins.

Even funnier, it only happens sometimes.

Even funnier, if I tweak the `document.spaceskip` value ever-so-slightly so that the whole document lays out with slightly different line breaks and the words break in a different place, which blocks fail and which succeed changes. I have a couple different styles with different fonts and line spacing inside the environoments and they all fail sometimes and succeed sometimes.

Here's a win:

![selection_156](https://cloud.githubusercontent.com/assets/173595/12787558/91aa4858-ca9e-11e5-9439-6cd1618e58f9.png)

Here's a fail:

![selection_155](https://cloud.githubusercontent.com/assets/173595/12787554/8a9a9ec8-ca9e-11e5-82a2-5d950e2e2430.png)

But wait. Here is that las fail — winning:

![selection_157](https://cloud.githubusercontent.com/assets/173595/12787620/d6f28d26-ca9e-11e5-9765-3acf570c785c.png)

The only difference between this and the previous compile is this:

``` diff
-\set[parameter=document.spaceskip,value=0.5en plus 0.45en minus 0.2en]
+\set[parameter=document.spaceskip,value=0.55en plus 0.45en minus 0.2en]
```

**Comment by mhosken** [comment]
Is this fail due to widow/orphan control? pulling back one line from the second page would leave an orphan. That the footnote reference is resolved on the previous page looks like it's due to the insertion not being pulled back when the page break occurs. Page breaking is hard!

Looking forward to Simon's reworked insertion stuff (if it hasn't already landed)

**Comment by simoncozens** [comment]
Martin: I haven't had time to look at this yet but the place I will start is the "pushback" routine's special handling of rskip and lskip glue. Maybe they're being removed but not properly reapplied.

**Comment by alerque** [comment]
As of build f9f36db I am unable to reproduce this issue. Like the wind, I don't know where it came from or where it went. I don't actually know that it's fixed—it could be that my metrics all changed just subtly enough to avoid the scenario—but I can't seem to make it fail now where-as it was happening repeatably at the time I opened this issue.

**Comment by alerque** [comment]
This isn't fixed, my document had just morphed enough that it wasn't symptomatic. Here is an MWE:

```TeX
\begin[papersize=180mm x 60mm]{document}
\nofolios
\font[family=Libertinus Serif,size=14pt]
\script[src=packages/lorem]
\lorem[words=110] % change this to 120 for two line wrap and no bug symptoms
{
\set[parameter=document.lskip,value=4em]
This is an indented environment
}
\end{document}
```

![selection_195](https://cloud.githubusercontent.com/assets/173595/14404049/1219e038-fe76-11e5-8b05-de462626a969.png)

For the life of me I can't figure out where the logic bug is, but finally hacked my document class with this quote environment to work around it:

```Lua
SILE.registerCommand("quote", function(options, content)
  local setback = options.setback or "2em"
  -- Begin hack around #262
  SILE.call("par")
  SILE.call("skip", { height="1.1em plus 2pt minus 1pt" })
  SILE.typesetter:typeset(" ")
  SILE.call("par")
  SILE.call("skip", { height="-1em plus 2pt minus 1pt" })
  -- End hack around #262
  SILE.settings.pushState()
  SILE.settings.temporarily(function()
    SILE.call("noindent")
    SILE.settings.set("document.rskip", SILE.nodefactory.newGlue(setback))
    SILE.settings.set("document.lskip", SILE.nodefactory.newGlue(setback))
    SILE.settings.set("current.parindent", SILE.nodefactory.zeroGlue)
    SILE.settings.set("document.parindent", SILE.nodefactory.zeroGlue)
    SILE.settings.set("document.parskip", SILE.nodefactory.newVglue("1.5ex"))
    SILE.process(content)
    SILE.settings.set("document.parskip", SILE.nodefactory.zeroVglue)
    SILE.typesetter:pushGlue(SILE.nodefactory.hfillGlue)
    SILE.call("novbreak")
    SILE.call("par")
    SILE.call("novbreak")
  end)
  SILE.settings.popState()
  SILE.call("medskip")
  SILE.call("novbreak")
  SILE.call("noindent")
end, "Typeset quototion blocks")
```

**Comment by simoncozens** [comment]
Disabling pushback (`\script[src=packages/debug]\disable-pushback`) fixes this, so it's a bug in `SILE.typesetter.pushBack`.

**Comment by simoncozens** [comment]
I think I have a fix for this but until we get regression tests together I can't be sure. :-(

**Comment by simoncozens** [comment]
...no, I haven't.

**Comment by simoncozens** [comment]
OK. I understand this bug. I don't know how to fix it yet; I want to see how TeX handles the same issue, so I need a dive into the TeX source.

**Comment by simoncozens** [comment]
...and TeX doesn't actually do this; it doesn't unpack the vboxes remaining on the vertical list after the frame break, because it assumes that all frames (pages) are the same size. But we need to do this, because our frames can well be different sizes. So this will need a lot of careful thought, unfortunately, about when lskip/rskip is added and when it isn't.

**Comment by alerque** [comment]
I'm sure there is something I'm missing here, but why can't the lskip value stay the same across page breaks until it's changed? What baffled be in trying to hack around this was that I couldn't seem to separate the failing line from the next paragraph. After that SILE gets its head back on and allows properties to be  set for the current environment, but without a dummy paragraph between the changes are being applied to content before (and logically isolated) from where they are set.

**Comment by simoncozens** [comment]
Suppose you have the following lines:

    1 My lskip is zero here.

      2 My lskip is 5em here, but the para
      3 wraps onto a second line and actually
      4 onto a third line.

    5 My lskip is zero here.

And now suppose the page builder is called after line 5 is processed, but the frame break falls between 2 and 3. Everything after line 2 goes back for reprocessing - it's taken off the vertical list and put onto the horizontal list, and then re-assembled into vboxes. This is done because the vboxes in the new frame may need to be a different width, if the frame is a different size. Left and right skips are deliberately *removed* from the list at this point, because, if the frame is a different size, they would end up in the wrong place - if the next page is considerably wider, you'd have a a 5em glue in between `actually` and `onto` sitting in the middle of the line.

When we put them back into vboxes, we redo the line breaking. But what value of lskip and rskip should we use to do this? Now, after line 5, the value of `document.lskip` is zero. We've thrown away the 5em glues, and we haven't anywhere stored the fact that this paragraph needs 5em lskip; in fact, we haven't got a data structure representing the concept of a paragraph.

I think what we need to do is store a whatsit node or something similar that stores every change in lskip/rskip value, so that it can be re-applied when we rebuild the lines.

**Comment by alerque** [comment]
Note in creating at est for this I ran into some interesting edge cases. I originally thought this only happened when one line worth of material was getting pushed and no more, but that isn't the case. In the test I wrote, compare changing the skip from 43em to 44em. Look, a two line fail. But it gets better. Compare 44em to 45em. Both end up pushing exactly the same amount of content across to the next page, but one fails and the other works fine.

**Comment by alerque** [comment]
In spite of the commit message advertisement, I haven't quite gotten this working yet. It works by happy accident — in al the ways that TeX would work but falls apart just  where Sile takes over. I think we're going to need a margin comparison routine. Just having a stack doesn't cut it because we don't want to break at the same places as before but when we do unpack a vbox that has different margins than  the  previous unpack we should start a new one in the output too.

**Comment by alerque** [comment]
Like a bad dream, this bug is back.

It's actually _working_ in the current iteration of the test (where <= 2 lines of content are fed through `pushBack()` but if the metrics are changed (say changing 43em to 53em) it becomes apparent that an lskip gets put in that is from the future.

**Comment by Omikhleia** [comment]
There was an MWE in an earlier message:
> This isn't fixed, my document had just morphed enough that it wasn't symptomatic. Here is an MWE (...)

With SILE 0.16.9, I couldn't reproduce the issue:
![Image](https://github.com/user-attachments/assets/92aecee6-e233-46ff-829f-7dd7f6232570)

It might be fixed, who knows?  This very old issue has lots of comments but no clear reproduction path, and has been inactive for a long time.
As part of the backlog cleaning review, I am therefore closing it, as
 - possibly solved
 - impossible to exactly understand from the old discussions if other points where at stake.

If you thing somethings is still amiss, please feel free to open a new issue, based on a recent version of SILE and with an explicit MWE and clearer expectations, for further investigation.
